#!/bin/sh
#mysql_backup.sh: backup mysql databases and keep newest 7 days backup. 
# 
# Last updated: 20 March 2006 
# ---------------------------------------------------------------------- 
# This is a free shell script under GNU GPL version 2.0 or above 
# Copyright (C) 2006 Sam Tang 
# Feedback/comment/suggestions : http://www.real-blog.com/ 
# ---------------------------------------------------------------------- 
# your mysql login information 
# db_user is mysql username 
# db_passwd is mysql password 
# db_host is mysql host 
# ----------------------------- 
db_user="" 
db_passwd="" 
db_host="localhost" 
# the directory for story your backup file. 
backup_dir="" 
# date format for backup file (dd-mm-yyyy) 
time="$(date +"%Y-%m-%d")" 
# mysql, mysqldump and some other bin's path 
MYSQL="" 
MYSQLDUMP="" 
MKDIR="/bin/mkdir" 
RM="/bin/rm" 
MV="/bin/mv" 
#GZIP="/bin/gzip"
GZIP="zip" 
# check the directory for store backup is writeable 
test ! -w $backup_dir && echo "Error: $backup_dir is un-writeable." && exit 0 
# the directory for story the newest backup 
test ! -d "$backup_dir/backup.0/" && $MKDIR "$backup_dir/backup.0/" 
# get all databases 
#all_db="$($MYSQL -u $db_user -h $db_host -p$db_passwd -Bse 'show databases')" 
all_db=""
for db in $all_db 
do 
$MYSQLDUMP -u $db_user -h $db_host -p$db_passwd $db >  "$backup_dir/backup.0/$db"
$GZIP -e -P sfds  "$backup_dir/backup.0/$time.$db.zip" "$backup_dir/backup.0/$db"
rm -rf "$backup_dir/backup.0/$db" 
done 
# delete the oldest backup 
test -d "$backup_dir/backup.8/" && $RM -rf "$backup_dir/backup.8" 
# rotate backup directory 
for int in 7 6 5 4 3 2 1 0 
do 
if(test -d "$backup_dir"/backup."$int") 
then 
next_int=`expr $int + 1` 
$MV "$backup_dir"/backup."$int" "$backup_dir"/backup."$next_int" 
fi 
done 

#backup upload&download file
#igzip -crv /filepath/ >> /backup/backup.1/$time.file.gz
$GZIP -r -e -P sfds /backup/backup.1/$time.file.zip /filepath/*
chmod -R 775  /backup/backup.1/
#exit 0;

/bin/cp -p /backup.1/* /BackupDir
removetime=`date +%Y-%m-%d --date '-1week'`
rm -f /BackupDir/$removetime.zip
rm -f /BackupDir/$removetime.zip
exit 0;


